### PR TITLE
The Coding Bootcamp Handbook

### PR DESCRIPTION
**Pull request by Weirdbuf**
#67

### CODE REVIEW

**Comment by miyaliu666** [comment]
谢谢 @Weirdbuf 的翻译！
翻译的时候请把英文原文去掉哦，直接写中文译文就行。不好意思，我稍后把这条补在 readme 里面。

**Comment by Weirdbuf** [comment]
@miyaliu666 好的

**Comment by miyaliu666** [comment]
提醒 @Weirdbuf 记得抽空翻译这篇文章哦:)
我们没有 deadline，但是如果你觉得自己近段时间都没有时间翻译的话，可以在这里留言，然后我们把文章 label 改为 Translation-needed，开放给别的贡献者认领。谢谢！

**Comment by Weirdbuf** [comment]
Hi Miya,
Sorry for this late reply. 
I am afraid I have to tell you the bad news that I decided to give up translating and focus on my daily course and projects. 
Hope you could find other translators soon.

**Comment by miyaliu666** [comment]
Thanks for this updating and thanks for your efforts:) Wish all the best on your daily course and projects.

**Pull request closed without merging**
